---

- name: Log into proper cluster
  shell: oc login {{openshift_host}} --token={{openshift_token}} --insecure-skip-tls-verify=true

- name: Create stage project
  shell: oc new-project {{jdg_project}}
  ignore_errors: yes
