---
- name: Log into proper cluster
  shell: oc login {{openshift_host}} --token={{openshift_token}} --insecure-skip-tls-verify=true

- name: Switch to proper project
  shell: oc project {{jdg_project}}

- name: Delete secret (if exists)
  shell: oc delete secret/jdg-app
  ignore_errors: yes

- name: Create secret
  shell: oc create secret generic jdg-app --from-literal=SITE={{site}} --from-literal=EXT_ADDR={{external_address}} --from-literal=DISCOVERY={{discovery_string}}
